### ISSUE TITLE
How to run on a existing set of values?

### ISSUE THREAD

**Issue by amahlaka** [lukix/genemo#54]
How can i pass a ready-made cost matrix to genemo and have it go thru all of the "points".
The example i found seems to randomly select only a part of it

**Comment by lukix** [comment]
Hi. Could you describe it in more detail? I don't quite understand your question. Maybe an example would be helpful (solution encoding, fitness function)?

**Comment by lukix** [comment]
We discussed it outside of GitHub. The question was about the traveling salesman problem.
Example of using GeneMO to solve TSP can be found in the `examples` directory:
https://github.com/lukix/genemo/blob/master/examples/example2-travelingSalesman.js

I'm closing this issue.
